const Text2SVG = require('./src/text2svg')
const Svg2TTF = require('./src/svg2ttf')
const Ttf2Woff2 = require('./src/ttf2woff2')
const Ttf2Woff = require('./src/ttf2woff')
const Opentype = require('./src/opentype')

// Text2SVG.start()
// Svg2TTF.start()
// Ttf2Woff2.start()
// Ttf2Woff.start()
Opentype.start()