const Text2SVG = require('./src/text2svg')
const Svg2TTF = require('./src/svg2ttf')
const TTF2Woff2 = require('./src/ttf2woff2')
const TTF2Woff = require('./src/ttf2woff')
const TTF2Eot = require('./src/ttf2eot')
const TTF2Svg = require('./src/ttf2svg')
const Opentype = require('./src/opentype')
const Webfont = require('./src/webfont')

Text2SVG.start()
// Svg2TTF.start()
// TTF2Woff2.start()
// TTF2Woff.start()
// TTF2Eot.start()
// TTF2Svg.start()
// Opentype.start()
// Webfont.start()